@startuml

class Usuario {}

class Reserva {}

class Cabana {}

' class Favoritos {}

class Comentario {}

class Valoracion {}

class Pago {}

class HistorialRolUsuario {}

class Rol {}

class PermisoDeRol {}

class Temporada {}

class HistorialPrecioCabana {}

class Senia {}

' class Grupo {}

class Oferta {}

class HistorialOfertas {}

Usuario "1" -- "0..*" Reserva : hace
' Usuario -- Favoritos
Usuario -- HistorialRolUsuario
HistorialRolUsuario -- Rol
Rol -- PermisoDeRol
Reserva "1" -- "1" Pago 
Reserva "1" -- "1" Senia
' Reserva -- Grupo
Cabana "1..*" --> "0..*" Reserva : tiene
Cabana -- Temporada
Cabana -- HistorialPrecioCabana
Cabana -- Oferta
Cabana -- Valoracion
Cabana -- Comentario
Oferta -- HistorialOfertas 

@enduml